// Content metadata for the math module "Fonctions de plusieurs variables"
// (official Paris-Saclay L2 Chimie UE, S3 — 5 ECTS, 18 h cours / 27 h TD).
// Single source of truth consumed by hubs, LessonMeta, ExerciseView and exams.
// Prose lives in the content.fr.mdx files; this file is metadata only.

import type { ExamMetaData, LessonMetaData, TdMetaData } from "./types";

export const MATH_MODULE_SLUG = "fonctions-plusieurs-variables";

export const MATH_LESSONS: LessonMetaData[] = [
  {
    id: "math-fmv-c00",
    slug: "00-remise-a-niveau",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Remise à niveau — le pont diagnostique",
      en: "Refresher — the diagnostic bridge",
      es: "Puesta al día — el puente diagnóstico",
    },
    provenance: "reconstruction",
    difficulty: 1,
    timeMinutes: 45,
    objectives: [
      {
        fr: "Vérifier les automatismes indispensables : dérivées, intégrales simples, EDO du premier ordre",
        en: "Check the essential skills: derivatives, simple integrals, and first-order ODEs",
        es: "Comprobar las destrezas esenciales: derivadas, integrales simples y EDO de primer orden",
      },
      {
        fr: "Résoudre un système linéaire 2×2 et calculer des valeurs propres",
        en: "Solve a 2×2 linear system and calculate eigenvalues",
        es: "Resolver un sistema lineal 2×2 y calcular valores propios",
      },
      {
        fr: "Convertir des coordonnées cartésiennes en polaires",
        en: "Convert Cartesian coordinates to polar coordinates",
        es: "Convertir coordenadas cartesianas en coordenadas polares",
      },
      {
        fr: "Reconnaître la nature d'une forme quadratique",
        en: "Identify the nature of a quadratic form",
        es: "Reconocer la naturaleza de una forma cuadrática",
      },
    ],
    relatedExercises: [],
  },
  {
    id: "math-fmv-c01",
    slug: "01-geometrie-coordonnees",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Géométrie du plan et de l'espace",
      en: "Geometry of the plane and space",
      es: "Geometría del plano y del espacio",
    },
    provenance: "officiel",
    difficulty: 2,
    timeMinutes: 90,
    objectives: [
      {
        fr: "Écrire l'équation paramétrique d'une droite et l'équation cartésienne d'un plan",
        en: "Write the parametric equation of a line and the Cartesian equation of a plane",
        es: "Escribir la ecuación paramétrica de una recta y la ecuación cartesiana de un plano",
      },
      {
        fr: "Calculer la distance d'un point à un plan",
        en: "Calculate the distance from a point to a plane",
        es: "Calcular la distancia de un punto a un plano",
      },
      {
        fr: "Passer entre coordonnées cartésiennes, polaires, cylindriques et sphériques",
        en: "Convert between Cartesian, polar, cylindrical, and spherical coordinates",
        es: "Pasar entre coordenadas cartesianas, polares, cilíndricas y esféricas",
      },
      {
        fr: "Retrouver les éléments différentiels dS et dV dans chaque système",
        en: "Derive the differential elements dS and dV in each system",
        es: "Obtener los elementos diferenciales dS y dV en cada sistema",
      },
      {
        fr: "Choisir le système de coordonnées adapté à la symétrie d'un problème de chimie",
        en: "Choose the coordinate system suited to the symmetry of a chemistry problem",
        es: "Elegir el sistema de coordenadas adaptado a la simetría de un problema de química",
      },
    ],
    prerequisites: ["math-fmv-c00"],
    relatedExercises: [
      "math-fmv-td1-01",
      "math-fmv-td1-02",
      "math-fmv-td1-03",
      "math-fmv-td1-04",
      "math-fmv-td1-05",
    ],
  },
  {
    id: "math-fmv-c02",
    slug: "02-surfaces-lignes-de-niveau",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Fonctions de plusieurs variables, surfaces et lignes de niveau",
      en: "Functions of several variables, surfaces, and level curves",
      es: "Funciones de varias variables, superficies y curvas de nivel",
    },
    provenance: "officiel",
    difficulty: 2,
    timeMinutes: 90,
    objectives: [
      {
        fr: "Représenter un champ scalaire par son graphe, ses lignes de niveau et ses fonctions partielles",
        en: "Represent a scalar field through its graph, level curves, and partial functions",
        es: "Representar un campo escalar mediante su gráfica, sus curvas de nivel y sus funciones parciales",
      },
      {
        fr: "Reconnaître les prototypes : plan, paraboloïdes elliptique et hyperbolique, colline gaussienne",
        en: "Recognize the prototypes: plane, elliptic and hyperbolic paraboloids, and Gaussian hill",
        es: "Reconocer los prototipos: plano, paraboloides elíptico e hiperbólico y colina gaussiana",
      },
      {
        fr: "Appliquer la méthode des ensembles de niveau (domaine, symétrie, géométrie en fonction de c)",
        en: "Apply the level-set method (domain, symmetry, and geometry as a function of c)",
        es: "Aplicar el método de los conjuntos de nivel (dominio, simetría y geometría en función de c)",
      },
      {
        fr: "Relier lignes de niveau et surfaces d'énergie potentielle en chimie",
        en: "Connect level curves to potential-energy surfaces in chemistry",
        es: "Relacionar las curvas de nivel con las superficies de energía potencial en química",
      },
    ],
    prerequisites: ["math-fmv-c01"],
    relatedExercises: ["math-fmv-td2-01", "math-fmv-td2-05"],
  },
  {
    id: "math-fmv-c03",
    slug: "03-limites-continuite",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Limites et continuité à plusieurs variables",
      en: "Limits and continuity in several variables",
      es: "Límites y continuidad en varias variables",
    },
    provenance: "officiel",
    difficulty: 3,
    timeMinutes: 90,
    objectives: [
      {
        fr: "Comprendre la définition de limite indépendante du chemin",
        en: "Understand the path-independent definition of a limit",
        es: "Comprender la definición de límite independiente del camino",
      },
      {
        fr: "Détruire une limite par deux chemins bien choisis",
        en: "Disprove a limit using two well-chosen paths",
        es: "Refutar un límite mediante dos caminos bien elegidos",
      },
      {
        fr: "Prouver une limite par majoration polaire |f| ≤ C·r^α",
        en: "Prove a limit using the polar bound |f| ≤ C·r^α",
        es: "Demostrar un límite mediante la cota polar |f| ≤ C·r^α",
      },
      {
        fr: "Interpréter la continuité comme robustesse d'un modèle chimique",
        en: "Interpret continuity as the robustness of a chemical model",
        es: "Interpretar la continuidad como robustez de un modelo químico",
      },
    ],
    prerequisites: ["math-fmv-c02"],
    relatedExercises: ["math-fmv-td2-02", "math-fmv-td2-03", "math-fmv-td2-04"],
  },
  {
    id: "math-fmv-c04",
    slug: "04-derivees-partielles-gradient",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Dérivées partielles, différentielle, plan tangent et gradient",
      en: "Partial derivatives, differential, tangent plane, and gradient",
      es: "Derivadas parciales, diferencial, plano tangente y gradiente",
    },
    provenance: "officiel",
    difficulty: 3,
    timeMinutes: 120,
    objectives: [
      {
        fr: "Calculer des dérivées partielles et écrire la différentielle df",
        en: "Calculate partial derivatives and write the differential df",
        es: "Calcular derivadas parciales y escribir la diferencial df",
      },
      {
        fr: "Construire le plan tangent en un point",
        en: "Construct the tangent plane at a point",
        es: "Construir el plano tangente en un punto",
      },
      {
        fr: "Interpréter le gradient : direction de plus forte pente, orthogonal aux lignes de niveau",
        en: "Interpret the gradient: direction of steepest ascent, orthogonal to level curves",
        es: "Interpretar el gradiente: dirección de máxima pendiente, ortogonal a las curvas de nivel",
      },
      {
        fr: "Calculer une dérivée directionnelle avec un vecteur unitaire",
        en: "Calculate a directional derivative using a unit vector",
        es: "Calcular una derivada direccional con un vector unitario",
      },
      {
        fr: "Appliquer la règle de la chaîne, y compris aux fonctions d'état G(T, P)",
        en: "Apply the chain rule, including to state functions G(T, P)",
        es: "Aplicar la regla de la cadena, también a las funciones de estado G(T, P)",
      },
    ],
    prerequisites: ["math-fmv-c03"],
    relatedExercises: ["math-fmv-td3-01", "math-fmv-td3-02", "math-fmv-td3-03"],
  },
  {
    id: "math-fmv-c05",
    slug: "05-propagation-incertitudes",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Propagation des incertitudes",
      en: "Uncertainty propagation",
      es: "Propagación de incertidumbres",
    },
    provenance: "officiel",
    difficulty: 3,
    timeMinutes: 90,
    objectives: [
      {
        fr: "Écrire la borne conservative |Δz| ≲ Σ |∂f/∂xᵢ| Δxᵢ",
        en: "Write the conservative bound |Δz| ≲ Σ |∂f/∂xᵢ| Δxᵢ",
        es: "Escribir la cota conservadora |Δz| ≲ Σ |∂f/∂xᵢ| Δxᵢ",
      },
      {
        fr: "Combiner des incertitudes indépendantes en quadrature",
        en: "Combine independent uncertainties in quadrature",
        es: "Combinar incertidumbres independientes en cuadratura",
      },
      {
        fr: "Utiliser la forme matricielle σ² = ∇fᵀ Σ ∇f avec covariances",
        en: "Use the matrix form σ² = ∇fᵀ Σ ∇f with covariances",
        es: "Utilizar la forma matricial σ² = ∇fᵀ Σ ∇f con covarianzas",
      },
      {
        fr: "Appliquer la propagation aux mesures de chimie : densité, loi de Beer–Lambert, loi d'Arrhenius",
        en: "Apply propagation to chemistry measurements: density, the Beer–Lambert law, and the Arrhenius law",
        es: "Aplicar la propagación a medidas de química: densidad, ley de Beer–Lambert y ley de Arrhenius",
      },
    ],
    prerequisites: ["math-fmv-c04"],
    relatedExercises: ["math-fmv-td3-04", "math-fmv-td3-05"],
  },
  {
    id: "math-fmv-c06",
    slug: "06-points-critiques-extrema",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Points critiques et extrema à deux variables",
      en: "Critical points and extrema in two variables",
      es: "Puntos críticos y extremos en dos variables",
    },
    provenance: "officiel",
    difficulty: 3,
    timeMinutes: 120,
    objectives: [
      {
        fr: "Trouver les points critiques par ∇f = 0",
        en: "Find critical points using ∇f = 0",
        es: "Encontrar los puntos críticos mediante ∇f = 0",
      },
      {
        fr: "Classifier avec la hessienne et le discriminant D = f_xx f_yy − f_xy²",
        en: "Classify using the Hessian and the discriminant D = f_xx f_yy − f_xy²",
        es: "Clasificar mediante la hessiana y el discriminante D = f_xx f_yy − f_xy²",
      },
      {
        fr: "Traiter les extrema globaux sur un domaine compact (intérieur, bord, coins)",
        en: "Handle global extrema on a compact domain (interior, boundary, and corners)",
        es: "Tratar los extremos globales en un dominio compacto (interior, borde y esquinas)",
      },
      {
        fr: "Découvrir les extrema sous contrainte par multiplicateurs de Lagrange (extension)",
        en: "Discover constrained extrema using Lagrange multipliers (extension)",
        es: "Descubrir los extremos con restricciones mediante multiplicadores de Lagrange (extensión)",
      },
      {
        fr: "Relier hessienne et stabilité d'un équilibre moléculaire (état de transition)",
        en: "Connect the Hessian to the stability of a molecular equilibrium (transition state)",
        es: "Relacionar la hessiana con la estabilidad de un equilibrio molecular (estado de transición)",
      },
    ],
    prerequisites: ["math-fmv-c04"],
    relatedExercises: [
      "math-fmv-td4-01",
      "math-fmv-td4-02",
      "math-fmv-td4-03",
      "math-fmv-td4-04",
      "math-fmv-td4-05",
    ],
  },
  {
    id: "math-fmv-c07",
    slug: "07-systemes-differentiels-portraits-de-phase",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Systèmes différentiels, trajectoires et portraits de phase",
      en: "Differential systems, trajectories, and phase portraits",
      es: "Sistemas diferenciales, trayectorias y retratos de fase",
    },
    provenance: "officiel",
    difficulty: 4,
    timeMinutes: 120,
    objectives: [
      {
        fr: "Lire un système x' = f(x,y), y' = g(x,y) comme un champ de vecteurs",
        en: "Read a system x' = f(x,y), y' = g(x,y) as a vector field",
        es: "Leer un sistema x' = f(x,y), y' = g(x,y) como un campo vectorial",
      },
      {
        fr: "Tracer les isoclines (nullclines) et localiser les équilibres",
        en: "Plot the nullclines and locate the equilibria",
        es: "Trazar las isoclinas (nullclines) y localizar los equilibrios",
      },
      {
        fr: "Linéariser avec la jacobienne et classifier localement",
        en: "Linearize using the Jacobian and classify locally",
        es: "Linealizar mediante la jacobiana y clasificar localmente",
      },
      {
        fr: "Modéliser des réseaux de réactions chimiques par des systèmes différentiels",
        en: "Model chemical reaction networks using differential systems",
        es: "Modelizar redes de reacciones químicas mediante sistemas diferenciales",
      },
    ],
    prerequisites: ["math-fmv-c04"],
    relatedExercises: ["math-fmv-td5-01", "math-fmv-td5-04"],
  },
  {
    id: "math-fmv-c08",
    slug: "08-systemes-conservatifs-hamiltoniens",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Systèmes conservatifs et hamiltoniens",
      en: "Conservative and Hamiltonian systems",
      es: "Sistemas conservativos y hamiltonianos",
    },
    provenance: "officiel",
    difficulty: 4,
    timeMinutes: 90,
    objectives: [
      {
        fr: "Reconnaître une intégrale première H et prouver dH/dt = 0",
        en: "Identify a first integral H and prove dH/dt = 0",
        es: "Reconocer una integral primera H y demostrar dH/dt = 0",
      },
      {
        fr: "Écrire un système hamiltonien plan x' = H_y, y' = −H_x",
        en: "Write a planar Hamiltonian system x' = H_y, y' = −H_x",
        es: "Escribir un sistema hamiltoniano plano x' = H_y, y' = −H_x",
      },
      {
        fr: "Opposer mouvement hamiltonien (suit les niveaux) et flot de gradient (les descend)",
        en: "Contrast Hamiltonian motion (follows level sets) with gradient flow (descends them)",
        es: "Contrastar el movimiento hamiltoniano (sigue los niveles) con el flujo de gradiente (desciende por ellos)",
      },
      {
        fr: "Utiliser H(q,p) = p²/2m + V(q) pour la mécanique d'une particule",
        en: "Use H(q,p) = p²/2m + V(q) for the mechanics of a particle",
        es: "Utilizar H(q,p) = p²/2m + V(q) para la mecánica de una partícula",
      },
    ],
    prerequisites: ["math-fmv-c07"],
    relatedExercises: ["math-fmv-td5-02", "math-fmv-td5-03"],
  },
  {
    id: "math-fmv-c09",
    slug: "09-systemes-lineaires-similitude",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Systèmes différentiels linéaires et classes de similitude",
      en: "Linear differential systems and similarity classes",
      es: "Sistemas diferenciales lineales y clases de semejanza",
    },
    provenance: "historique",
    difficulty: 4,
    timeMinutes: 120,
    objectives: [
      {
        fr: "Résoudre X' = AX par diagonalisation et valeurs propres",
        en: "Solve X' = AX using diagonalization and eigenvalues",
        es: "Resolver X' = AX mediante diagonalización y valores propios",
      },
      {
        fr: "Traiter un bloc de Jordan et l'exponentielle de matrice",
        en: "Handle a Jordan block and the matrix exponential",
        es: "Tratar un bloque de Jordan y la exponencial de una matriz",
      },
      {
        fr: "Classifier les portraits par le plan trace–déterminant",
        en: "Classify phase portraits using the trace–determinant plane",
        es: "Clasificar los retratos de fase mediante el plano traza–determinante",
      },
      {
        fr: "Appliquer aux cinétiques chimiques séquentielles A → B → C",
        en: "Apply the method to sequential chemical kinetics A → B → C",
        es: "Aplicar el método a cinéticas químicas secuenciales A → B → C",
      },
    ],
    prerequisites: ["math-fmv-c07"],
    relatedExercises: [
      "math-fmv-td6-01",
      "math-fmv-td6-02",
      "math-fmv-td6-03",
      "math-fmv-td6-04",
      "math-fmv-td6-05",
    ],
  },
  {
    id: "math-fmv-c10",
    slug: "10-oscillateur-harmonique-modes-normaux",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "Oscillateur harmonique et modes normaux",
      en: "Harmonic oscillator and normal modes",
      es: "Oscilador armónico y modos normales",
    },
    provenance: "officiel",
    difficulty: 4,
    timeMinutes: 120,
    objectives: [
      {
        fr: "Réduire mx'' + γx' + kx = 0 à un système du premier ordre",
        en: "Reduce mx'' + γx' + kx = 0 to a first-order system",
        es: "Reducir mx'' + γx' + kx = 0 a un sistema de primer orden",
      },
      {
        fr: "Distinguer les régimes sous-amorti, critique et sur-amorti via ζ",
        en: "Distinguish the underdamped, critically damped, and overdamped regimes using ζ",
        es: "Distinguir los regímenes subamortiguado, críticamente amortiguado y sobreamortiguado mediante ζ",
      },
      {
        fr: "Étudier l'oscillateur forcé et la résonance (extension)",
        en: "Study the forced oscillator and resonance (extension)",
        es: "Estudiar el oscilador forzado y la resonancia (extensión)",
      },
      {
        fr: "Trouver les modes normaux d'oscillateurs couplés et l'effet isotopique",
        en: "Find the normal modes of coupled oscillators and the isotope effect",
        es: "Encontrar los modos normales de osciladores acoplados y el efecto isotópico",
      },
    ],
    prerequisites: ["math-fmv-c09"],
    relatedExercises: [
      "math-fmv-td7-01",
      "math-fmv-td7-02",
      "math-fmv-td7-03",
      "math-fmv-td7-04",
    ],
  },
];

export const MATH_TDS: TdMetaData[] = [
  {
    id: "math-fmv-td1",
    slug: "td-1",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 1 — Géométrie et systèmes de coordonnées",
      en: "TD 1 — Geometry and coordinate systems",
      es: "TD 1 — Geometría y sistemas de coordenadas",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td1-01", tdId: "math-fmv-td1", title: { fr: "Plans sécants", en: "Intersecting planes", es: "Planos secantes" }, difficulty: 3, lessonIds: ["math-fmv-c01"] },
      { id: "math-fmv-td1-02", tdId: "math-fmv-td1", title: { fr: "Preuve par choix de coordonnées", en: "Proof by choosing coordinates", es: "Demostración mediante elección de coordenadas" }, difficulty: 3, lessonIds: ["math-fmv-c01"] },
      { id: "math-fmv-td1-03", tdId: "math-fmv-td1", title: { fr: "Distance entre droites gauches", en: "Distance between skew lines", es: "Distancia entre rectas alabeadas" }, difficulty: 4, lessonIds: ["math-fmv-c01"] },
      { id: "math-fmv-td1-04", tdId: "math-fmv-td1", title: { fr: "Jacobien sphérique", en: "Spherical Jacobian", es: "Jacobiano esférico" }, difficulty: 4, lessonIds: ["math-fmv-c01"] },
      { id: "math-fmv-td1-05", tdId: "math-fmv-td1", title: { fr: "Géométrie moléculaire", en: "Molecular geometry", es: "Geometría molecular" }, difficulty: 4, lessonIds: ["math-fmv-c01"] },
    ],
  },
  {
    id: "math-fmv-td2",
    slug: "td-2",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 2 — Surfaces, lignes de niveau et limites",
      en: "TD 2 — Surfaces, level curves, and limits",
      es: "TD 2 — Superficies, curvas de nivel y límites",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td2-01", tdId: "math-fmv-td2", title: { fr: "Reconstruire une surface", en: "Reconstructing a surface", es: "Reconstruir una superficie" }, difficulty: 3, lessonIds: ["math-fmv-c02"] },
      { id: "math-fmv-td2-02", tdId: "math-fmv-td2", title: { fr: "Échec par les chemins", en: "Failure along paths", es: "Fallo por caminos" }, difficulty: 3, lessonIds: ["math-fmv-c03"] },
      { id: "math-fmv-td2-03", tdId: "math-fmv-td2", title: { fr: "Une limite qui exige une majoration", en: "A limit that requires a bound", es: "Un límite que exige una cota" }, difficulty: 4, lessonIds: ["math-fmv-c03"] },
      { id: "math-fmv-td2-04", tdId: "math-fmv-td2", title: { fr: "Continue mais non différentiable", en: "Continuous but not differentiable", es: "Continua pero no diferenciable" }, difficulty: 4, lessonIds: ["math-fmv-c03", "math-fmv-c04"] },
      { id: "math-fmv-td2-05", tdId: "math-fmv-td2", title: { fr: "Paysage gaussien", en: "Gaussian landscape", es: "Paisaje gaussiano" }, difficulty: 4, lessonIds: ["math-fmv-c02", "math-fmv-c06"] },
    ],
  },
  {
    id: "math-fmv-td3",
    slug: "td-3",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 3 — Différentielle, gradient et incertitudes",
      en: "TD 3 — Differential, gradient, and uncertainties",
      es: "TD 3 — Diferencial, gradiente e incertidumbres",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td3-01", tdId: "math-fmv-td3", title: { fr: "Plan tangent", en: "Tangent plane", es: "Plano tangente" }, difficulty: 3, lessonIds: ["math-fmv-c04"] },
      { id: "math-fmv-td3-02", tdId: "math-fmv-td3", title: { fr: "Gradient et surface de niveau", en: "Gradient and level surface", es: "Gradiente y superficie de nivel" }, difficulty: 3, lessonIds: ["math-fmv-c04"] },
      { id: "math-fmv-td3-03", tdId: "math-fmv-td3", title: { fr: "Composition et jacobienne", en: "Composition and Jacobian", es: "Composición y jacobiana" }, difficulty: 4, lessonIds: ["math-fmv-c04"] },
      { id: "math-fmv-td3-04", tdId: "math-fmv-td3", title: { fr: "Incertitude sur une densité", en: "Uncertainty in a density", es: "Incertidumbre en una densidad" }, difficulty: 3, lessonIds: ["math-fmv-c05"] },
      { id: "math-fmv-td3-05", tdId: "math-fmv-td3", title: { fr: "Étalonnage corrélé", en: "Correlated calibration", es: "Calibración correlacionada" }, difficulty: 5, lessonIds: ["math-fmv-c05"] },
    ],
  },
  {
    id: "math-fmv-td4",
    slug: "td-4",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 4 — Points critiques et extrema",
      en: "TD 4 — Critical points and extrema",
      es: "TD 4 — Puntos críticos y extremos",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td4-01", tdId: "math-fmv-td4", title: { fr: "Classification complète", en: "Complete classification", es: "Clasificación completa" }, difficulty: 3, lessonIds: ["math-fmv-c06"] },
      { id: "math-fmv-td4-02", tdId: "math-fmv-td4", title: { fr: "Points dégénérés", en: "Degenerate points", es: "Puntos degenerados" }, difficulty: 4, lessonIds: ["math-fmv-c06"] },
      { id: "math-fmv-td4-03", tdId: "math-fmv-td4", title: { fr: "Énergie quadratique couplée", en: "Coupled quadratic energy", es: "Energía cuadrática acoplada" }, difficulty: 4, lessonIds: ["math-fmv-c06"] },
      { id: "math-fmv-td4-04", tdId: "math-fmv-td4", title: { fr: "Minimum sous contrainte", en: "Constrained minimum", es: "Mínimo con restricciones" }, difficulty: 4, lessonIds: ["math-fmv-c06"] },
      { id: "math-fmv-td4-05", tdId: "math-fmv-td4", title: { fr: "Paysage d'état de transition", en: "Transition-state landscape", es: "Paisaje de estado de transición" }, difficulty: 5, lessonIds: ["math-fmv-c06"] },
    ],
  },
  {
    id: "math-fmv-td5",
    slug: "td-5",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 5 — Portraits de phase et systèmes non linéaires",
      en: "TD 5 — Phase portraits and nonlinear systems",
      es: "TD 5 — Retratos de fase y sistemas no lineales",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td5-01", tdId: "math-fmv-td5", title: { fr: "Isoclines", en: "Nullclines", es: "Isoclinas" }, difficulty: 3, lessonIds: ["math-fmv-c07"] },
      { id: "math-fmv-td5-02", tdId: "math-fmv-td5", title: { fr: "Intégrale première", en: "First integral", es: "Integral primera" }, difficulty: 4, lessonIds: ["math-fmv-c08"] },
      { id: "math-fmv-td5-03", tdId: "math-fmv-td5", title: { fr: "Flot de gradient", en: "Gradient flow", es: "Flujo de gradiente" }, difficulty: 4, lessonIds: ["math-fmv-c08"] },
      { id: "math-fmv-td5-04", tdId: "math-fmv-td5", title: { fr: "Le piège de la linéarisation", en: "The linearization trap", es: "La trampa de la linealización" }, difficulty: 5, lessonIds: ["math-fmv-c07", "math-fmv-c08"] },
    ],
  },
  {
    id: "math-fmv-td6",
    slug: "td-6",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 6 — Systèmes linéaires et similitude",
      en: "TD 6 — Linear systems and similarity",
      es: "TD 6 — Sistemas lineales y semejanza",
    },
    provenance: "historique",
    exercises: [
      { id: "math-fmv-td6-01", tdId: "math-fmv-td6", title: { fr: "Diagonalisation", en: "Diagonalization", es: "Diagonalización" }, difficulty: 3, lessonIds: ["math-fmv-c09"] },
      { id: "math-fmv-td6-02", tdId: "math-fmv-td6", title: { fr: "Bloc de Jordan", en: "Jordan block", es: "Bloque de Jordan" }, difficulty: 4, lessonIds: ["math-fmv-c09"] },
      { id: "math-fmv-td6-03", tdId: "math-fmv-td6", title: { fr: "Conception inverse", en: "Inverse design", es: "Diseño inverso" }, difficulty: 4, lessonIds: ["math-fmv-c09"] },
      { id: "math-fmv-td6-04", tdId: "math-fmv-td6", title: { fr: "Réaction séquentielle A → B → C", en: "Sequential reaction A → B → C", es: "Reacción secuencial A → B → C" }, difficulty: 4, lessonIds: ["math-fmv-c09"] },
      { id: "math-fmv-td6-05", tdId: "math-fmv-td6", title: { fr: "Exponentielle de matrice", en: "Matrix exponential", es: "Exponencial de una matriz" }, difficulty: 5, lessonIds: ["math-fmv-c09"] },
    ],
  },
  {
    id: "math-fmv-td7",
    slug: "td-7",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    title: {
      fr: "TD 7 — Oscillateur harmonique et modes normaux",
      en: "TD 7 — Harmonic oscillator and normal modes",
      es: "TD 7 — Oscilador armónico y modos normales",
    },
    provenance: "reconstruction",
    exercises: [
      { id: "math-fmv-td7-01", tdId: "math-fmv-td7", title: { fr: "Régimes d'amortissement", en: "Damping regimes", es: "Regímenes de amortiguamiento" }, difficulty: 3, lessonIds: ["math-fmv-c10"] },
      { id: "math-fmv-td7-02", tdId: "math-fmv-td7", title: { fr: "Décroissance de l'énergie", en: "Energy decay", es: "Decaimiento de la energía" }, difficulty: 4, lessonIds: ["math-fmv-c10"] },
      { id: "math-fmv-td7-03", tdId: "math-fmv-td7", title: { fr: "Deux oscillateurs couplés", en: "Two coupled oscillators", es: "Dos osciladores acoplados" }, difficulty: 5, lessonIds: ["math-fmv-c10"] },
      { id: "math-fmv-td7-04", tdId: "math-fmv-td7", title: { fr: "Déplacement isotopique", en: "Isotopic shift", es: "Desplazamiento isotópico" }, difficulty: 4, lessonIds: ["math-fmv-c10"] },
    ],
  },
];

export const MATH_EXAMS: ExamMetaData[] = [
  {
    id: "math-fmv-exam-cc",
    slug: "cc",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    kind: "cc",
    title: {
      fr: "Contrôle continu — reconstruction",
      en: "Contrôle continu (continuous assessment) — reconstruction",
      es: "Contrôle continu (evaluación continua) — reconstrucción",
    },
    durationMinutes: 45,
    totalPoints: 20,
    topics: ["math-fmv-c01", "math-fmv-c03", "math-fmv-c04", "math-fmv-c05", "math-fmv-c06"],
    provenance: "reconstruction",
  },
  {
    id: "math-fmv-exam-partiel",
    slug: "partiel",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    kind: "partiel",
    title: {
      fr: "Partiel — reconstruction",
      en: "Partiel (midterm exam) — reconstruction",
      es: "Partiel (parcial) — reconstrucción",
    },
    durationMinutes: 90,
    totalPoints: 20,
    topics: ["math-fmv-c04", "math-fmv-c05", "math-fmv-c06", "math-fmv-c09"],
    provenance: "reconstruction",
  },
  {
    id: "math-fmv-exam-final",
    slug: "final",
    moduleSlug: MATH_MODULE_SLUG,
    subject: "math",
    kind: "final",
    title: {
      fr: "Examen final — reconstruction",
      en: "Final exam — reconstruction",
      es: "Examen final — reconstrucción",
    },
    durationMinutes: 120,
    totalPoints: 40,
    topics: [
      "math-fmv-c06",
      "math-fmv-c07",
      "math-fmv-c08",
      "math-fmv-c09",
      "math-fmv-c10",
    ],
    provenance: "reconstruction",
  },
];
