"use client";
import { useState, type ReactNode } from 'react';
import { parseIp, formatIp, subnetInfo, maskFromPrefix, toBinary, type Fragment } from '@/lib/cs/ipv4';
import { ARP_FIELDS, COURSE_ROUTES, TD_ROUTES, matchingRoutes, deliveryEvents, safeFragments, probeResult } from '@/lib/cs/ipLab';
import { Choice, Explain, Numeric } from './shared';

export type IPActivityKind = 'header' | 'subnet' | 'forward' | 'arp' | 'fragment' | 'icmp' | 'rip' | 'ospf' | 'decode';
function Bench({title,children}:{title:string;children:ReactNode}) {
  return <section className="nl-workbench ip-activity"><p className="nl-eyebrow">Manipuler puis expliquer sur une copie</p><h3>{title}</h3>{children}</section>;
}
function Check({label,expected,why}:{label:string;expected:string;why:string}) {
  const [value,setValue]=useState(''); const [checked,setChecked]=useState(false);
  const clean=(x:string)=>x.trim().toLowerCase().replace(/\s+/g,'');
  return <div className="nl-question"><label>{label}<input value={value} onChange={e=>{setValue(e.target.value);setChecked(false);}} /></label><button onClick={()=>setChecked(true)}>Vérifier</button>{checked && <p role="status" className={clean(value)===clean(expected)?'nl-good':'nl-feedback'}>{clean(value)===clean(expected)?'Oui. ':'À revoir. '}{why}</p>}<Explain title="Indice et réponse"><p>{why} Réponse : <strong>{expected}</strong>.</p></Explain></div>;
}
function Header() {
  const [ihl,setIhl]=useState(5),[total,setTotal]=useState(1420),[ttl,setTtl]=useState(8),[hops,setHops]=useState(0);
  const valid=Number.isInteger(total) && total>=ihl*4 && total<=65535;
  return <Bench title="Ouvrir l’en-tête IPv4"><p>L’IHL compte des mots de 32 bits. Prédis les octets d’en-tête et de données avant d’ouvrir la réponse.</p><div className="nl-inline"><label>IHL <input type="number" min={5} max={15} value={ihl} onChange={e=>setIhl(Math.max(5,Math.min(15,Math.trunc(Number(e.target.value))||5)))} /></label><label>Longueur totale (octets)<input type="number" min={20} max={65535} value={total} onChange={e=>setTotal(Number(e.target.value))}/></label><label>TTL initial<input type="number" min={1} max={255} value={ttl} onChange={e=>{setTtl(Math.max(1,Math.min(255,Math.trunc(Number(e.target.value))||1)));setHops(0);}}/></label></div>
    <div className="ip-packet"><span>Version 4</span><span>IHL {ihl}</span><span>TOS</span><span>Longueur {total}</span><span>Identification</span><span>DF / MF / offset</span><span>TTL {Math.max(0,ttl-hops)}</span><span>Protocole</span><span>Checksum</span><span>IP source → IP destination</span></div>
    {valid?<><Numeric key={`${ihl}-${total}`} question="Combien d’octets de données ?" answer={total-ihl*4} unit="octets" why={`L’en-tête occupe ${ihl} × 4 = ${ihl*4} octets ; soustrais-le de la longueur totale.`}/><button disabled={hops>=ttl} onClick={()=>setHops(hops+1)}>Traverser un routeur</button><button onClick={()=>setHops(0)}>Revenir au départ</button><p role="status">{hops>=ttl?'TTL épuisé : rejet ; une erreur ICMP Time Exceeded peut être renvoyée.':`${hops} routeur(s) : TTL ${ttl-hops}. Le checksum de l’en-tête doit refléter cette modification.`}</p></>:<p role="alert">La longueur totale doit contenir tout l’en-tête et rester au plus égale à 65 535.</p>}
    <p className="nl-takeaway">Sans l’interface : IHL = 6, longueur = 100. Explique pourquoi la charge utile vaut 76 octets et pas 80. Cette expérience isole l’acheminement sans options modifiées, NAT ou fragmentation.</p>
  </Bench>;
}
function Subnet() {
  const [address,setAddress]=useState('137.10.45.126'),[prefix,setPrefix]=useState(25),[peer,setPeer]=useState('137.10.45.200');
  const ip=parseIp(address),other=parseIp(peer);const info=ip===null?null:subnetInfo(ip,prefix);
  return <Bench title="Placer les ordinateurs dans le bon sous-réseau"><p>Exemple du cours : le réseau 137.10.45.0/24 devient deux /25. Modifie le masque : les câbles ne changent pas, mais la décision « voisin local ou passerelle » dépend du préfixe configuré.</p><div className="nl-inline"><label>Ordinateur A<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Préfixe /<input type="number" min={8} max={30} value={prefix} onChange={e=>setPrefix(Math.max(8,Math.min(30,Math.trunc(Number(e.target.value))||8)))}/></label><label>Ordinateur B<input value={peer} onChange={e=>setPeer(e.target.value)}/></label></div>
    {info && other!==null?<><div className="ip-topology"><span>A · {address}/{prefix}</span>{(other & maskFromPrefix(prefix))===(ip! & maskFromPrefix(prefix))?<span>← même LAN →</span>:<><span>← LAN 1 →</span><span>R · passerelle</span><span>← LAN 2 →</span></>}<span>B · {peer}</span></div><p>Schéma conceptuel : les LAN physiques doivent être configurés en accord avec les préfixes ; changer seulement un masque ne déplace aucune machine.</p><pre>{`IP     ${toBinary(ip!)}\nMasque ${toBinary(maskFromPrefix(prefix))}\nET     ${toBinary(info.network)}`}</pre><Check key={`${address}/${prefix}`} label="Adresse du réseau de A" expected={formatIp(info.network)} why="Applique le ET bit à bit entre adresse et masque."/><Check key={`broadcast-${address}/${prefix}`} label="Adresse de diffusion du réseau de A" expected={formatIp(info.broadcast)} why="Conserve la partie réseau, puis mets tous les bits hôte à 1."/><Choice key={`${address}/${peer}/${prefix}`} question="Selon son masque, A considère-t-il B comme local ?" options={['Oui : chercher la MAC de B','Non : chercher la MAC de la passerelle']} answer={(other & maskFromPrefix(prefix))===(ip! & maskFromPrefix(prefix))?0:1} why="Compare les deux adresses après le même ET avec le masque de A. Un nom DNS commun ne suffit jamais."/><Explain title="Plan d’adressage et capacité"><p>Réseau {formatIp(info.network)}/{prefix}, masque {formatIp(maskFromPrefix(prefix))}, diffusion {formatIp(info.broadcast)}. Plage {formatIp(info.firstHost)} à {formatIp(info.lastHost)} ; {info.hostCount} adresses hôte selon la convention usuelle du TD (réseau et broadcast exclus).</p></Explain></>:<p role="alert">Entre deux IPv4 valides : quatre entiers entre 0 et 255.</p>}
    <p className="nl-takeaway">Sur papier : pour 12 sous-réseaux d’au moins 12 machines dans un /24, combien de bits emprunter ? Vérifie séparément le nombre de sous-réseaux et la capacité de chacun.</p><Explain title="Correction du transfert"><p>4 bits donnent 16 sous-réseaux ; il reste 4 bits hôte, donc 14 machines par /28. Le masque est 255.255.255.240.</p></Explain>
  </Bench>;
}
function Forward() {
  const [preset,setPreset]=useState('cours'),[destination,setDestination]=useState('193.52.71.8'),[pick,setPick]=useState<number|null>(null),[host,setHost]=useState(false),[dropDefault,setDropDefault]=useState(false);
  const original=preset==='cours'?COURSE_ROUTES:TD_ROUTES;
  const routes=[...original.filter(r=>!dropDefault || r.prefix!==0),...(host?[{network:destination,prefix:32,via:null,iface:'Interface dédiée (variante)'}]:[])];
  const matches=matchingRoutes(destination,routes), best=matches[0];
  return <Bench title="Tu es le routeur : choisis la bonne ligne"><p>Pour le TD11, les /8 sont une hypothèse classful explicite : le dessin ne fournit pas de masques. Prédis le prochain saut et l’interface. Une route directe signifie que l’IP à résoudre sur le lien est celle du destinataire ; sinon, celle de la passerelle.</p><div className="nl-inline"><label>Table<select value={preset} onChange={e=>{setPreset(e.target.value);setDestination(e.target.value==='cours'?'193.52.71.8':'40.0.0.1');setPick(null);}}><option value="cours">Cours · diapositive 38 · R1</option><option value="td">TD IP · exercice 11 · C</option></select></label><label>IP destination<input value={destination} onChange={e=>{setDestination(e.target.value);setPick(null);}}/></label></div><label><input type="checkbox" checked={host} onChange={e=>{setHost(e.target.checked);setPick(null);}}/> Variante : ajouter une route /32 vers cette machine</label><label><input type="checkbox" checked={dropDefault} onChange={e=>{setDropDefault(e.target.checked);setPick(null);}}/> Variante : retirer la route par défaut</label>
    <div className="nl-table-scroll"><table><thead><tr><th>Destination</th><th>Prochain saut</th><th>Interface</th><th>Décision</th></tr></thead><tbody>{routes.map((r,i)=><tr key={i}><td>{r.network}/{r.prefix}</td><td>{r.via||'Direct'}</td><td>{r.iface}</td><td><button aria-pressed={pick===i} onClick={()=>setPick(i)}>Choisir {i+1}</button></td></tr>)}</tbody></table></div><button aria-pressed={pick===-1} onClick={()=>setPick(-1)}>Aucune route</button>
    {parseIp(destination)===null?<p role="alert">Adresse IPv4 invalide.</p>:pick!==null?<p role="status" className={pick===(best??-1)?'nl-good':'nl-feedback'}>{pick===(best??-1)?'Bonne décision. ':'Recompare les préfixes. '}{best===undefined?'Aucune route ne correspond : le paquet ne peut pas être acheminé avec cette table.':`Ligne ${best+1} : /${routes[best].prefix} est le plus long préfixe correspondant. Résolution locale de ${routes[best].via||destination}, sortie ${routes[best].iface}.`}</p>:null}
    <Explain title="Voir toutes les correspondances et la solution"><p>{best===undefined?'Aucune correspondance.':`Lignes correspondantes, de la plus précise à la moins précise : ${matches.map(i=>i+1).join(', ')}. Choisir ${best+1}. La route /0 ne remplace pas une route plus précise.`}</p></Explain><p className="nl-takeaway">Sans aide : dans la table de R1, indique la sortie vers 193.52.74.9 puis vers 8.8.8.8. Le coût n’est pas un substitut à la règle du plus long préfixe.</p>
  </Bench>;
}
function Arp() {
  const [remote,setRemote]=useState(true),[warm,setWarm]=useState(false),[step,setStep]=useState(0);
  const events=deliveryEvents(remote,warm),event=events[Math.min(step,events.length-1)];
  return <Bench title="IP garde le destinataire ; Ethernet choisit le voisin"><p>Illustration pédagogique : A = 192.168.1.10/24, B = {remote?'192.168.2.20/24':'192.168.1.20/24'}. R relie les deux LAN avec .1 sur chaque réseau. A connaît déjà l’IP de B.</p><div className="nl-options"><button aria-pressed={remote} onClick={()=>{setRemote(!remote);setStep(0);}}>{remote?'B est distant':'B est local'} · changer</button><button aria-pressed={warm} onClick={()=>{setWarm(!warm);setStep(0);}}>{warm?'Cache ARP de A rempli':'Cache ARP de A vide'} · changer</button></div><Choice key={String(remote)} question="À qui A doit-il adresser sa première trame IP ?" options={['MAC de B','MAC de R']} answer={remote?1:0} why={remote?'B est hors du /24 : la première trame vise la passerelle, même si le paquet IP vise B.':'B est dans le même /24 : livraison locale, sans traverser R.'}/>
    <div className="ip-topology"><span>A</span><span>LAN 1</span><span>R</span><span>{remote?'LAN 2':'LAN 1'}</span><span>B</span></div><p className="nl-eyebrow">Étape {step+1}/{events.length} · {event.protocol}</p><h4>{event.title} : {event.from} → {event.to}</h4><p role="status">{event.detail}</p><div className="nl-inline"><button disabled={step===0} onClick={()=>setStep(step-1)}>Précédent</button><button disabled={step===events.length-1} onClick={()=>setStep(step+1)}>Étape suivante</button><button onClick={()=>setStep(0)}>Recommencer</button></div><Explain title="Voir tout l’échange"><ol>{events.map(e=><li key={e.title}><strong>{e.title}.</strong> {e.detail}</li>)}</ol></Explain><p className="nl-takeaway">Sur copie : dessine les deux enveloppes Ethernet d’un envoi distant, en conservant A → B dans les champs IP. Puis explique ce que change un cache ARP déjà rempli.</p>
  </Bench>;
}
function FragmentTable({fragments}:{fragments:Fragment[]}) {
 const [values,setValues]=useState<Record<string,string>>({}),[checked,setChecked]=useState(false);
 const fields=[['dataLength','Données'],['totalLength','Longueur IP'],['offsetUnits','Offset /8'],['mf','MF']] as const;
 const correct=fragments.every((f,i)=>fields.every(([field])=>values[`${i}-${field}`]?.trim()!=='' && Number(values[`${i}-${field}`])===f[field]));
 return <div><div className="nl-table-scroll"><table><thead><tr><th>Fragment</th>{fields.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{fragments.map((f,i)=><tr key={i}><th>{i+1}</th>{fields.map(([field,label])=>{const key=`${i}-${field}`,valid=values[key]?.trim()!=='' && Number(values[key])===f[field];return <td key={key}><label><span className="sr-only">Fragment {i+1}, {label}</span><input aria-invalid={checked&&!valid} inputMode="numeric" value={values[key]||''} onChange={e=>{setValues({...values,[key]:e.target.value});setChecked(false);}}/>{checked&&<small>{valid?'✓':'À revoir'}</small>}</label></td>;})}</tr>)}</tbody></table></div><button onClick={()=>setChecked(true)}>Vérifier mon tableau</button>{checked&&<p role="status">{correct?'Toutes les cellules sont cohérentes. Explique maintenant pourquoi les offsets se rapportent au datagramme initial.':'Reprends les cellules signalées : longueur = données + 20, offset = position initiale / 8 ; MF ne vaut 0 que pour la fin du datagramme original. La table corrigée reste accessible juste après.'}</p>}</div>;
}
function Fragmentation() {
  const [data,setData]=useState(1400),[mtu,setMtu]=useState(620),[second,setSecond]=useState(0),[df,setDf]=useState(false),[stage,setStage]=useState(1);
  const stages=safeFragments(data,second?[mtu,second]:[mtu]); const selected=stages?.[Math.min(stage,stages.length-1)];
  return <Bench title="Construire la table des fragments"><p>Point de départ du cours : 1 400 octets de données, en-tête de 20 octets, MTU IP de 620. Ici la MTU inclut l’en-tête IP, pas celui de la trame.</p><div className="nl-options"><button onClick={()=>{setData(1400);setMtu(620);setSecond(0);setDf(false);setStage(1);}}>Cours · 1400 / 620</button><button onClick={()=>{setData(109);setMtu(128);setSecond(0);setDf(false);setStage(1);}}>TD · Ex. 4</button><button onClick={()=>{setData(2000);setMtu(1024);setSecond(512);setDf(false);setStage(2);}}>TD · Ex. 9</button><button onClick={()=>{setData(2048);setMtu(1010);setSecond(504);setDf(false);setStage(2);}}>Final · Ex. 2</button></div><p>Préréglage du final : les MTU IP affichées ont déjà été diminuées des en-têtes de trame (1024−14 et 512−8). Dans l’exercice 4 du TD IP, « 129 octets » désigne le paquet entier : on saisit donc 109 données.</p><div className="nl-inline"><label>Données (octets)<input type="number" value={data} onChange={e=>setData(Number(e.target.value))}/></label><label>MTU IP du premier lien<input type="number" value={mtu} onChange={e=>setMtu(Number(e.target.value))}/></label><label>MTU IP du second lien (0 : aucun)<input type="number" value={second} onChange={e=>setSecond(Number(e.target.value))}/></label></div><label><input type="checkbox" checked={df} onChange={e=>setDf(e.target.checked)}/> DF = 1 : interdire la fragmentation</label>
    {!stages?<p role="alert">Données : 1 à 65 515 ; MTU : 28 à 65 535 octets, entiers. Une MTU trop petite ne peut pas porter un fragment de ce modèle.</p>:df && (data+20>mtu || (second>0 && data+20>second))?<p role="status">Le datagramme trop grand est rejeté au premier lien incompatible. ICMP type 3, code 4 : fragmentation nécessaire et DF positionné. Aucun fragment n’est envoyé sur ce lien.</p>:<><div className="nl-options">{stages.map((_,i)=><button key={i} aria-pressed={Math.min(stage,stages.length-1)===i} onClick={()=>setStage(i)}>{i===0?'Avant les liens':`Après le lien ${i}`}</button>)}</div><Numeric key={`${data}-${mtu}-${second}-${stage}`} question="Combien de fragments à cette étape ?" answer={selected!.length} why="Chaque fragment reçu est redécoupé séparément si nécessaire ; un routeur ne réassemble pas les fragments pour les redécouper."/><Explain title="À toi — compléter chaque cellule du tableau"><FragmentTable key={`${data}-${mtu}-${second}-${stage}`} fragments={selected!}/></Explain><Explain title="Table corrigée — accessible immédiatement"><div className="nl-table-scroll"><table><thead><tr><th>Fragment</th><th>Données</th><th>Longueur IP</th><th>Offset /8</th><th>MF</th></tr></thead><tbody>{selected!.map((f,i)=><tr key={i}><td>{i+1}</td><td>{f.dataLength}</td><td>{f.totalLength}</td><td>{f.offsetUnits}</td><td>{f.mf}</td></tr>)}</tbody></table></div></Explain>{selected!.length>1 && <Numeric key={`offset-${data}-${mtu}-${second}-${stage}`} question="Offset du deuxième fragment, en unités de 8 octets ?" answer={selected![1].offsetUnits} why={`Le premier octet de ce fragment est à la position ${selected![1].offsetUnits*8} dans les données d’origine. Divise par 8, pas par la MTU.`}/>}</>}
    <Explain title="Méthode et limites du modèle"><p>Charge maximale = 8 × partie entière((MTU − 20)/8). Les fragments gardent l’identification. L’offset se mesure depuis le début des données originales. Le dernier morceau d’un fragment hérite de son MF ; il ne devient pas forcément 0. Ce simulateur fixe l’en-tête à 20 octets : le TD explique séparément la copie des options.</p></Explain><p className="nl-takeaway">Sur papier : retrouve 620, 620, 220 pour les longueurs et 0, 75, 150 pour les offsets du cas initial ; MF vaut 1, 1, 0.</p>
  </Bench>;
}
function Icmp() {
  const [ttl,setTtl]=useState(1),[silent,setSilent]=useState(false); const result=probeResult(ttl,3,silent?2:0)!;
  return <Bench title="Explorer un chemin avec le TTL"><p>Illustration : A → R1 → R2 → R3 → B. Une nouvelle sonde ICMP Echo Request part avec le TTL choisi. Ce modèle représente des sondes ICMP ; un traceroute UDP reçoit généralement « port inaccessible » à destination.</p><div className="ip-topology">{['A','R1','R2','R3','B'].map(n=><span key={n} aria-current={n===result.at?'step':undefined}>{n}{n===result.at?' ← sonde':''}</span>)}</div><label>TTL initial<input type="range" min={1} max={5} value={ttl} onChange={e=>setTtl(Number(e.target.value))}/>{ttl}</label><label><input type="checkbox" checked={silent} onChange={e=>setSilent(e.target.checked)}/> R2 ne répond pas aux sondes expirées</label><Choice key={`${ttl}-${silent}`} question="Quelle observation à la source ?" options={['ICMP temps dépassé','Réponse Echo de B','Pas de réponse (*)']} answer={!result.reply?2:result.arrived?1:0} why={!result.reply?'L’absence de réponse ne prouve pas une panne du chemin : R2 peut filtrer ses réponses tout en acheminant les sondes dont le TTL suffit.':result.arrived?'Le TTL suffit pour franchir les trois routeurs. B répond à la requête Echo.':`Le TTL atteint zéro sur ${result.at}, qui peut renvoyer ICMP type 11, code 0 à A.`}/><Explain title="Observation complète"><p>{result.reply?`${result.at} répond : type ${result.type}, code ${result.code}.`:`${result.at} laisse expirer la sonde sans réponse : *. Augmente le TTL pour observer les sauts suivants.`} Des routes asymétriques, de l’équilibrage et des files d’attente peuvent modifier les résultats réels ; une trace seule ne fournit pas les masques des réseaux.</p></Explain><p className="nl-takeaway">Sur copie : pourquoi R3 peut-il apparaître après une ligne de trois astérisques ? Pourquoi un temps aller-retour plus petit au saut suivant n’est-il pas impossible ?</p>
  </Bench>;
}
function Rip() {
  const [failed,setFailed]=useState(false),[metric,setMetric]=useState(2),[round,setRound]=useState(0),[poison,setPoison]=useState(false);
  return <Bench title="RIP : une rumeur de route après une panne"><p>Illustration bornée : A atteint D en 1 saut et B utilise A en 2 sauts. Après la panne A–D, A pourrait croire l’ancienne annonce de B. Les mises à jour ci-dessous alternent entre les deux routeurs ; ce ne sont pas des ticks obligatoires de 30 secondes.</p><div className="ip-topology"><span>D</span><span>{failed?'× panne':'—'}</span><span>A</span><span>↔</span><span>B</span></div><label><input type="checkbox" checked={poison} onChange={e=>{setPoison(e.target.checked);setMetric(2);setRound(0);setFailed(false);}}/> Horizon partagé avec antidote : B annonce 16 à A pour une route apprise de A</label><button onClick={()=>{setFailed(true);setMetric(poison?16:2);setRound(0);}}>Couper A–D</button><button disabled={!failed || metric>=16} onClick={()=>{setMetric(Math.min(16,metric+1));setRound(round+1);}}>Recevoir la prochaine annonce</button><button onClick={()=>{setFailed(false);setMetric(2);setRound(0);}}>Réinitialiser</button><p role="status">{!failed?'Avant panne : A → D = 1 ; B → D via A = 2.':metric>=16?'Métrique 16 : destination inaccessible pour RIP. Avec antidote, A refuse la route que B annonce via A ; B doit ensuite apprendre le retrait de A. Le jeu résume ces deux annonces.':round===0?'B conserve encore sa route de coût 2 via A. A vient de perdre son accès direct.':`${round%2?'A':'B'} accepte maintenant ${metric} sauts via ${round%2?'B':'A'}. La route annoncée revient pourtant par lui : boucle.`}</p><Explain title="Pourquoi les coûts augmentent"><p>A entend 2 de B et calcule 3 ; B entend 3 de A et calcule 4, etc. La borne 16 arrête cette montée dans RIP. L’antidote empêche cette boucle à deux routeurs mais ne constitue pas une preuve d’absence de toute boucle dans un réseau plus grand. RIP utilise UDP 520, des annonces périodiques d’environ 30 s et un délai d’expiration de route de 180 s dans le cours.</p></Explain><p className="nl-takeaway">Sans aide : distingue « métrique 16 », « 16 routeurs utilisables » et « délai de convergence ». Puis justifie l’annonce empoisonnée.</p>
  </Bench>;
}
const FLOOD_NEIGHBORS:Record<string,string[]>={A:['B','C'],B:['A','C','D'],C:['A','B','D'],D:['B','C']};
function Ospf() {
  const [known,setKnown]=useState(['A']),[frontier,setFrontier]=useState(['A']);
  function advance(){const next=[...new Set(frontier.flatMap(n=>FLOOD_NEIGHBORS[n]))].filter(n=>!known.includes(n));setKnown([...known,...next]);setFrontier(next);}
  return <Bench title="OSPF : diffuser une information avant de calculer"><p>Illustration dans une seule aire : liens A–B, A–C, B–C, B–D, C–D. A produit une nouvelle annonce d’état de liens. Prédis qui l’apprend après chaque tour ; chaque routeur élimine les doublons de cette même annonce.</p><div className="ip-topology">{Object.keys(FLOOD_NEIGHBORS).map(n=><span key={n}>{n} · {known.includes(n)?'annonce connue':'en attente'}</span>)}</div><button disabled={known.length===4} onClick={advance}>Diffuser aux voisins</button><button onClick={()=>{setKnown(['A']);setFrontier(['A']);}}>Recommencer</button><p role="status">{known.length}/4 routeurs connaissent l’annonce de A. {known.length===4?'Tous peuvent mettre à jour cette partie de leur base topologique. Il faut les annonces des autres routeurs pour disposer de toute la carte.':''}</p><Explain title="Du réseau réel à Dijkstra"><p>HELLO découvre et entretient les voisinages. Les annonces décrivent des liens ; leur diffusion construit une base cohérente dans l’aire. Chaque routeur calcule ensuite son propre arbre avec Dijkstra. Une annonce de lien n’est pas un vecteur donnant toutes les distances finales.</p><p>Dans le cours, les aires sont reliées au backbone 0 par des routeurs de bordure. On ne diffuse pas indistinctement toutes les annonces dans toutes les aires : leur type et leur portée comptent. Ce jeu isole la diffusion intra-aire, sans simuler les adjacences ni les types de LSA.</p></Explain><Choice question="Pourquoi B et C ne transmettent-ils pas sans fin la même annonce entre eux ?" options={['Ils identifient les annonces déjà reçues','OSPF supprime tous les cycles physiques','Dijkstra bloque les messages']} answer={0} why="La diffusion utilise l’identité et la fraîcheur des annonces. Le calcul local de Dijkstra vient ensuite."/><p className="nl-takeaway">Sur copie : distingue découverte des voisins, diffusion de la topologie et calcul des routes. Place une aire périphérique, son routeur de bordure et l’aire 0.</p>
  </Bench>;
}
function Decode() {
  const [field,setField]=useState(0),[guess,setGuess]=useState(''),[checked,setChecked]=useState(false);
  return <Bench title="Lire les octets d’un en-tête ARP"><p>Entraînement sur les champs communs du TD12. Les trames intégrales et leur champ original <code>00 1C</code> sont conservés dans le TD ; celui-ci représente une longueur, pas l’EtherType <code>08 06</code>.</p><div className="nl-options">{ARP_FIELDS.map((f,i)=><button key={i} aria-pressed={field===i} onClick={()=>{setField(i);setGuess('');setChecked(false);}}><code>{f[1]}</code><small> · octets {i*2}–{i*2+1}</small></button>)}</div><label>Quel champ occupe cette position ?<select value={guess} onChange={e=>{setGuess(e.target.value);setChecked(false);}}><option value="">Choisir</option>{ARP_FIELDS.map(f=><option key={f[0]}>{f[0]}</option>)}</select></label><button onClick={()=>setChecked(true)}>Vérifier</button>{checked&&<p role="status" className={guess===ARP_FIELDS[field][0]?'nl-good':'nl-feedback'}>{guess===ARP_FIELDS[field][0]?'Oui. ':'Reprends la position et la taille du champ. '}{ARP_FIELDS[field][2]}</p>}<Explain title="Tous les champs"><ol>{ARP_FIELDS.map(f=><li key={f[0]}><code>{f[1]}</code> : {f[0]}. {f[2]}</li>)}</ol></Explain><p className="nl-takeaway">Sur la trame originale : repère ensuite les 6 octets de la MAC émettrice et les 4 octets de son IP. Deux champs peuvent avoir les mêmes octets « 00 01 » : seule leur position permet de les interpréter.</p>
  </Bench>;
}
export function IPActivity({kind}:{kind:IPActivityKind}) {
  const components={header:Header,subnet:Subnet,forward:Forward,arp:Arp,fragment:Fragmentation,icmp:Icmp,rip:Rip,ospf:Ospf,decode:Decode};
  const Component=components[kind];return <Component/>;
}
