"use client";
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { NETWORK_THEMES, networkResources, type ResourceKind } from '@/lib/cs/networkResources';
import type { Locale } from '@/lib/i18n/config';
import { rememberLanguage } from './language';
const KINDS:Record<ResourceKind,string>={cours:'Cours',exercice:'Exercices',jeu:'Jeux',annale:'Annales et entraînements',fiche:'Fiches',source:'Supports originaux'};
export function ResourceDirectory({locale='fr',inside=false}:{locale?:Locale;inside?:boolean}){
  const [kind,setKind]=useState('tous'),[theme,setTheme]=useState('tous'),[query,setQuery]=useState('');
  const resources=useMemo(()=>networkResources(locale),[locale]);
  const visible=resources.filter(r=>(kind==='tous'||r.kind===kind)&&(theme==='tous'||r.theme===theme)&&`${r.title} ${r.note||''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <section className="nl-root network-directory" aria-labelledby="network-directory-title"><h2 id="network-directory-title">{locale==='fr'?'Retrouver les ressources par thème':locale==='en'?'Resources by topic':'Recursos por tema'}</h2><p>{locale==='fr'?'Cours, exercices nommés, jeux et annales : choisis ce que tu veux travailler. Les nouvelles activités et les documents du cours sont en français.':locale==='en'?'The new workshop and original course documents are in French. Classic lessons remain available in your language.':'El nuevo taller y los documentos originales están en francés. Las lecciones clásicas siguen disponibles en tu idioma.'}</p><div className="nl-inline"><label>Thème<select aria-label="Thème" value={theme} onChange={e=>setTheme(e.target.value)}><option value="tous">Tous les thèmes</option>{NETWORK_THEMES.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><label>Type<select aria-label="Type" value={kind} onChange={e=>setKind(e.target.value)}><option value="tous">Toutes les ressources</option>{Object.entries(KINDS).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><label>Rechercher<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ARP, masque, TD4…"/></label></div><p role="status">{visible.length} ressource(s)</p>{NETWORK_THEMES.map(([id,title])=>{const entries=visible.filter(r=>r.theme===id);return entries.length?<section key={id} className="network-theme"><h3>{title}</h3><ul className="network-resource-list">{entries.map(r=>{const href=r.href.startsWith('#')?(inside?r.href:`/fr/cs/reseaux/atelier?from=${locale}${r.href}`):r.href;return <li key={r.id}><span className="lesson-meta-chip">{KINDS[r.kind]}</span> <Link href={href} onClick={()=>{if(!inside&&r.french)rememberLanguage(locale);}}>{r.title}</Link>{r.french&&<small> · FR</small>}{r.note&&<small> · {r.note}</small>}</li>;})}</ul></section>:null;})}<p>Les sujets reconstruits sont signalés séparément des documents fournis. Aucun résultat ne conditionne l’accès à une ressource.</p></section>;
}
